apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utleggstrekk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  webproxy: true
  resources:
    limits:
      cpu: 2000m
      memory: 12Gi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  azure:
    application:
      enabled: true
      allowAllUsers: true
  ingresses:
    - https://sokos-utleggstrekk.intern.dev.nav.no
  vault:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:utleggstrekkformidling
  envFrom:
    - secret: sokos-utleggstrekk-mq
  env:
    - name: USE_AUTHENTICATION
      value: "false"
    - name: SKE_REST_URL
      value: https://api-test.sits.no/api/trekkpaalegg/v1/
    - name: POSTGRES_HOST_NAME
      value: b27dbvl035.preprod.local
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_NAME
      value: sokos-utleggstrekk
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: LOG_APPENDER
      value: CONSOLE
    - name: MQ_HOSTNAME
      value: mqls02.preprod.local
    - name: MQ_PORT
      value: "1413"
    - name: MQ_QUEUE_MANAGER_NAME
      value: MQLS02
    - name: MQ_CHANNEL
      value: Q1_UTLEGGSTREKK
    - name: MQ_QUEUE_NAME
      value: QA.DY_231.OB04_INNRAPPORTERING_TREKK


