apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sokos-utleggstrekk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  ingresses:
    - https://sokos-utleggstrekk.intern.dev.nav.no
  image: {{image}}
  port: 8080
  ttl: 3h
  replicas:
    max: 1
    min: 1
  webproxy: true
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
