apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utleggstrekk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 2
  secureLogs:
    enabled: true
  webproxy: true
  resources:
    limits:
      cpu: 2000m
      memory: 12Gi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
  ingresses:
    - https://sokos-skattekort-dolly.intern.dev.nav.no
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:utleggstrekkformidling
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/oseskatt_q1-sokos_skattekort_dolly_q1
        mountPath: /var/run/secrets/nais.io/database-user
  env:
    - name: SKE_REST_URL
      value: https://api-test.sits.no/api/utleggstrekk/v1/
    - name: POSTGRES_HOST
      value: b27dbvl030.preprod.local
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_NAME
      value: sokos-utleggstrekk
    - name: VAULT_MOUNTPATH
      value: postgresql/preprod-fss/
    - name: LOG_APPENDER
      value: CONSOLE
