include file("application.conf")

application {
  scheduler {
    isActive = false
  }
}

skeConfig {
  skeRestUrl = "https://api-test.sits.no/api/trekkpaalegg/v1"
  skeOrgNr = 971648199
  skeKontoNr = 70213997155
  skeTSSId = 80000423362
}

mqProperties {
  hostname = "10.53.17.118"
  port = 1413
  mqQueueManagerName = MQLS02
  mqChannelName = "Q1_UTLEGGSTREKK"
  queueName = "QA.Q1_231.OB04_TREKK_FRASKATT_JSON"
  replyQueueName = "QA.Q1_SOKOS_UTLEGGSTREKK.KVITTERING"
}

postgresConfig {
  host = "dev-pg.intern.nav.no"
  port = 5432
  username = "sokos-utleggstrekk"
}