ktor {
  environment = test
}

application {
  profile = test
  appName = "sokos-utleggstrekk"
  namespace = "okonomi-test"

  configuration {
    security {
      azure {
        clientId = "clientId"
        wellKnownUrl = "wellKnownUrl"
      }
    }
  }
}