include file("application.conf")

application {
  profile = PROD
}

skeConfig {
  skeRestUrl = "https://api.skatteetaten.no/api/trekkpaalegg/v1"
  skeOrgNr = 936295266
  skeKontoNr = 76940569814
  skeTSSId = 80001018463
}

mqProperties {
  hostname = "mpls02.adeo.no"
  port = 1414
  mqQueueManagerName = MPLS02
  mqChannelName = "P_UTLEGGSTREKK"
  queueName = "QA.P231.OB04_TREKK_FRASKATT_JSON"
  replyQueueName = "QA.P_SOKOS_UTLEGGSTREKK.KVITTERING"
}

maskinportenClientConfig {
  systemBrukerClaim = 995277670
}

unleashProperties {
  enabled = false
}