include "application.conf"

ktor {
  environment = dev
}

application {
  profile = DEV
}

mqProperties {
  hostname = "mqls02.preprod.local"
  port = 1413
  mqQueueManagerName = MQLS02
  mqChannelName = "Q1_UTLEGGSTREKK"
  queueName = "QA.Q1_231.OB04_TREKK_FRASKATT_JSON"
  replyQueueName = "QA.Q1_SOKOS_UTLEGGSTREKK.KVITTERING"
}

maskinportenClientConfig {
  systemBrukerClaim = 312978083
}