include file("defaults.properties")
ktor {
  environment = test
}

application {
  profile = TEST
  appName = "sokos-utleggstrekk"
  namespace = "okonomi-test"

  configuration {
    security {
      azure {
        clientId = ${AZURE_APP_CLIENT_ID}
        wellKnownUrl = ${AZURE_APP_WELL_KNOWN_URL}
      }
    }
  }
}

skeConfig {
  skeRestUrl = "https://api-test.sits.no/api/trekkpaalegg/v1"
  skeOrgNr = 971648199
  skeKontoNr = 70213997155
  skeTSSId = 80000423362
}

maskinportenClientConfig {
  clientId = ${MASKINPORTEN_CLIENT_ID}
  wellKnownUrl = ${MASKINPORTEN_WELL_KNOWN_URL}
  rsaKeyString = ${MASKINPORTEN_CLIENT_JWK}
  scopes = ${MASKINPORTEN_SCOPES}
}

slackConfig {
  url = ${SOKOS_UTLEGGSTREKK_SLACK_WEBHOOK_URL}
}