include file("defaults.properties")

ktor {
  environment = local
}

application {
  profile = LOCAL
  appName = "sokos-utleggstrekk"
  appName = ${?NAIS_APP_NAME}
  namespace = okonomi
  naisPodName = "local-no-pod"
  naisPodName = ${?NAIS_POD_NAME}

  scheduler {
    isActive = true
  }
}

mqProperties {
  username = ${MQ_USERNAME}
  password = ${MQ_PASSWORD}
}

maskinportenClientConfig {
  clientId = ${MASKINPORTEN_CLIENT_ID}
  wellKnownUrl = ${MASKINPORTEN_WELL_KNOWN_URL}
  rsaKeyString = ${MASKINPORTEN_CLIENT_JWK}
  scopes = ${MASKINPORTEN_SCOPES}
  systemBrukerClaim = ${MASKINPORTEN_SYSTEMBRUKER_CLAIM}
}

postgresConfig {
  password = ${POSTGRES_PASSWORD}
  jdbcUrl = ${POSTGRES_JDBC_URL}
  user = ${POSTGRES_USERNAME}
}

slackConfig {
  url = ${SOKOS_UTLEGGSTREKK_SLACK_WEBHOOK_URL}
}

unleashProperties {
  unleashApi = ${?UNLEASH_SERVER_API_URL}
  apiKey = ${?UNLEASH_SERVER_API_TOKEN}
  environment = ${?UNLEASH_SERVER_API_ENV}
  enabled = true
}