ktor {
  environment = local
}

application {
  profile = LOCAL
  appName = "sokos-utleggstrekk"
  namespace = okonomi

  configuration {
    security {
      azure {
        clientId = ${AZURE_APP_CLIENT_ID}
        wellKnownUrl = ${AZURE_APP_WELL_KNOWN_URL}
      }
    }
  }
}

AZURE_APP_CLIENT_ID = azure-app-client-id
AZURE_APP_WELL_KNOWN_URL = azure-app-well-known-url