ktor {
  environment = prod
}

application {
  profile = PROD
  appName = "sokos-utleggstrekk"
  appName = ${?NAIS_APP_NAME}
  namespace = okonomi
  naisPodName = "local-no-pod"
  naisPodName = ${?NAIS_POD_NAME}

  scheduler {
    isActive = true
  }
}

skeConfig {
  skeRestUrl = "https://api.skatteetaten.no/api/trekkpaalegg/v1"
  skeOrgNr = 936295266
  skeKontoNr = 76940569814
  skeTSSId = 80001018463
}

maskinportenClientConfig {
  systemBrukerClaim = 995277670
  clientId = ${MASKINPORTEN_CLIENT_ID}
  wellKnownUrl = ${MASKINPORTEN_WELL_KNOWN_URL}
  scopes = ${MASKINPORTEN_SCOPES}
  rsaKeyString = ${MASKINPORTEN_CLIENT_JWK}
}

mqProperties {
  hostname = "mpls02.adeo.no"
  port = 1414
  mqQueueManagerName = MPLS02
  mqChannelName = "P_UTLEGGSTREKK"
  queueName = "QA.P231.OB04_TREKK_FRASKATT_JSON"
  replyQueueName = "QA.P_SOKOS_UTLEGGSTREKK.KVITTERING"
  username = ${MQ_USERNAME}
  password = ${MQ_PASSWORD}
  userAuth = true
}

postgresConfig {
  host = ${POSTGRES_HOST}
  port = ${POSTGRES_PORT}
  username = ${POSTGRES_USERNAME}
  password = ${POSTGRES_PASSWORD}
  jdbcUrl = ${POSTGRES_JDBC_URL}
  user = ${POSTGRES_USERNAME}
  name = "sokos-utleggstrekk"
}

slackConfig {
  url = ${SOKOS_UTLEGGSTREKK_SLACK_WEBHOOK_URL}
}

unleashProperties {
  enabledByDefault = false
  unleashApi = ${?UNLEASH_SERVER_API_URL}
  apiKey = ${?UNLEASH_SERVER_API_TOKEN}
  environment = ${?UNLEASH_SERVER_API_ENV}
}