apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-utleggstrekk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  webproxy: true
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: okonomi-unleash-api.nav.cloud.nais.io
        - host: mpls02.adeo.no
          ports:
            - port: 1413
        - host: api.skatteetaten.no
  ingresses:
    - https://sokos-utleggstrekk.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  vault:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:trekkpaalegg
  envFrom:
    - secret: sokos-utleggstrekk-secrets
    - secret: sokos-utleggstrekk-unleash-api-token
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        autoBackupHour: 3
        tier: db-custom-1-3840
        databases:
          - name: sokos-utleggstrekk
            envVarPrefix: POSTGRES
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
          - name: "cloudsql.logical_decoding"
            value: "on"
  env:
    - name: APPLICATION_PROFILE
      value: PROD
    - name: USE_AUTHENTICATION
      value: "true"
    - name: SKE_REST_URL
      value: https://api.skatteetaten.no/api/trekkpaalegg/v1
    - name: POSTGRES_NAME
      value: sokos-utleggstrekk
    - name: LOG_APPENDER
      value: CONSOLE
    - name: MQ_HOSTNAME
      value: mpls02.adeo.no
    - name: MQ_PORT
      value: "1414"
    - name: MQ_QUEUE_MANAGER_NAME
      value: MPLS02
    - name: MQ_CHANNEL
      value: P_UTLEGGSTREKK
    - name: MQ_QUEUE_NAME
      value: QA.P231.OB04_TREKK_FRASKATT_JSON
    - name: MQ_REPLYQUEUE_NAME
      value: QA.P_SOKOS_UTLEGGSTREKK.KVITTERING
    - name: SCHEDULER_MINUTES
      value: "45"
    - name: UNLEASHED_DEFAULT_IS_ENABLED
      value: "false"