apiVersion: "nais.io/v1alpha1"
kind: "Job"
metadata:
  name: sokos-utleggstrekk
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 1
    max: 1
  webproxy: true
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp

    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: okonomi-unleash-api.nav.cloud.nais.io
        - host: mqls02.preprod.local
        - host: api-test.sits.no
  ingresses:
    - https://sokos-utleggstrekk.gcp.intern.dev.nav.no
  vault:
    enabled: true
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: skatteetaten:trekkpaalegg
  envFrom:
    - secret: sokos-utleggstrekk-secrets
  gcp:
    sqlInstances:
      - type: POSTGRES_18
        highAvailability: true
        diskAutoresize: true
        pointInTimeRecovery: true
        autoBackupHour: 3
        tier: db-custom-1-3840
        databases:
          - name: sokos-utleggstrekk
            envVarPrefix: POSTGRES
  env:
    - name: USE_AUTHENTICATION
      value: "false"
    - name: SKE_REST_URL
      value: https://api-test.sits.no/api/trekkpaalegg/v1
    - name: POSTGRES_NAME
      value: sokos-utleggstrekk
    - name: LOG_APPENDER
      value: CONSOLE
    - name: MQ_HOSTNAME
      value: mqls02.preprod.local
    - name: MQ_PORT
      value: "1413"
    - name: MQ_QUEUE_MANAGER_NAME
      value: MQLS02
    - name: MQ_CHANNEL
      value: Q1_UTLEGGSTREKK
    - name: MQ_QUEUE_NAME
      value: QA.Q1_231.OB04_TREKK_FRASKATT_JSON
    - name: MQ_REPLYQUEUE_NAME
      value: QA.Q1_SOKOS_UTLEGGSTREKK.KVITTERING



