/**
 * Utleggstrekk API
 * #### Beskrivelse   OpenAPI-dokumentasjon for Skatteetatens tjenester for uthenting av trekk.  ##### Lenker    - [Tekniskdokumentasjon](https://skatteetaten.github.io/beta-apier/utleggstrekk) 
 *
 * OpenAPI spec version: 0.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package no.nav.utleggstrekk.models

data class MidlertidigStans (

    val startPeriode: String? = null,
    val sluttPeriode: String? = null
) {
}