name: Deploy Unleash

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/unleash.yaml'
      - '.nais/dev/unleash-dev.yaml'
      - '.nais/dev/unleash-prod.yaml'

env:
  TZ: Europe/Oslo

jobs:
  deploy-dev:
    permissions:
      id-token: write
      contents: read
    name: Deploy to dev-gcp
    uses: navikt/mob-gha-workflows/.github/workflows/unleash-deploy.yaml@dac7a1ac47e76110d90af301b2152057c215c867 # ratchet:navikt/mob-gha-workflows/.github/workflows/unleash-deploy.yaml@v1.0.0
    with:
      cluster: dev-gcp
      resource: .nais/dev/unleash-dev.yaml

  deploy-prod:
    permissions:
      id-token: write
      contents: read
    name: Deploy to prod-gcp
    uses: navikt/mob-gha-workflows/.github/workflows/unleash-deploy.yaml@dac7a1ac47e76110d90af301b2152057c215c867 # ratchet:navikt/mob-gha-workflows/.github/workflows/unleash-deploy.yaml@v1.0.0
    with:
      cluster: prod-gcp
      resource: .nais/prod/unleash-prod.yaml